# Generated by Django 6.0.5 on 2026-05-29 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='°C', max_digits=5)),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='mmHg')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='mmHg')),
                ('heart_rate', models.PositiveIntegerField(help_text='bpm')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='breaths/min')),
                ('oxygen_saturation', models.DecimalField(decimal_places=2, help_text='%', max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('chief_complaint', models.CharField(max_length=500)),
                ('symptoms_description', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('consultation', 'Under Consultation'), ('treated', 'Treated'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('admitted_ward', models.CharField(blank=True, max_length=100)),
                ('discharge_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('triage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='triage.triagerecord')),
            ],
            options={
                'ordering': [models.Case(models.When(priority='critical', then=0), models.When(priority='high', then=1), models.When(priority='medium', then=2), models.When(priority='low', then=3), default=4), 'arrival_time'],
            },
        ),
    ]
