# Generated by Django 6.0.5 on 2026-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, help_text='Optional (e.g. M.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', 'Select Department'), ('triage_emergency', 'Triage / Emergency'), ('opd', 'Outpatient Department (OPD)'), ('internal_medicine', 'Internal Medicine'), ('pediatrics', 'Pediatrics'), ('ob_gyn', 'OB-GYN / Maternal Health'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('admitting_records', 'Admitting / Medical Records')], max_length=50),
        ),
    ]
