# Generated by Django 6.0.5 on 2026-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('triage_emergency', 'Triage / Emergency'), ('opd', 'Outpatient Department (OPD)'), ('internal_medicine', 'Internal Medicine'), ('pediatrics', 'Pediatrics'), ('ob_gyn', 'OB-GYN / Maternal Health'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('admitting_records', 'Admitting / Medical Records')], default='triage_emergency', help_text='Department this patient is assigned to', max_length=50),
        ),
    ]
